namespace Tsgen.Emit;

uses
  System.Text,
  System.Collections.Generic,
  Tsgen.Ir,
  Tsgen.Nrt;

type
  EnumStyle = public enum (Numeric, StringUnion);

  {
    Single-file emitter for the MVP (docs/DESIGN.md §7.3 also describes a
    split-file / ES-module layout, deferred -- see HANDOFF.md §11).

    Also where Stage 3 (type mapping) and --nrt-unknown-policy get
    applied -- the IR carries raw ClrTypeName/Nullability so this is the
    first point where a policy choice is actually made.
  }
  DtsEmitter = public static class
  private
    class method ResolveNullable(aKind: NullabilityKind; aUnknownPolicy: NrtUnknownPolicy): Boolean;
    begin
      if aKind = NullabilityKind.IsNullable then
        result := true
      else if aKind = NullabilityKind.IsNotNullable then
        result := false
      else
        result := (aUnknownPolicy = NrtUnknownPolicy.TreatAsNullable);
    end;

    class method EmitType(aSb: StringBuilder; aType: IrTypeLite; aEnumStyle: EnumStyle; aUnknownPolicy: NrtUnknownPolicy; aPad: String);
    begin
      if aType.Kind = IrTypeKindLite.EnumLike then begin
        if aEnumStyle = EnumStyle.Numeric then begin
          aSb.AppendLine(aPad + 'export enum ' + aType.Name + ' {');
          for each ev in aType.EnumValues do
            aSb.AppendLine(aPad + '  ' + ev.Name + ' = ' + ev.NumericValue.ToString() + ',');
          aSb.AppendLine(aPad + '}');
        end
        else begin
          var namesSb := new StringBuilder;
          for i: Int32 := 0 to aType.EnumValues.Count - 1 do begin
            if i > 0 then namesSb.Append(' | ');
            namesSb.Append('"' + aType.EnumValues[i].Name + '"');
          end;
          aSb.AppendLine(aPad + 'export type ' + aType.Name + ' = ' + namesSb.ToString() + ';');
        end;
      end
      else begin
        aSb.AppendLine(aPad + 'export interface ' + aType.Name + ' {');
        for each m in aType.Members do begin
          var tsType := TypeMapper.MapClrTypeName(m.ClrTypeName);
          if tsType = 'unknown' then
            writeLn('Warning: no type mapping for ' + m.ClrTypeName + ' (member ' + aType.Name + '.' + m.Name + '), emitting "unknown"');

          var opt := '';
          if ResolveNullable(m.Nullability, aUnknownPolicy) then opt := ' | null';
          aSb.AppendLine(aPad + '  ' + m.Name + ': ' + tsType + opt + ';');
        end;
        aSb.AppendLine(aPad + '}');
      end;
    end;

  public
    class method Emit(aAssembly: IrAssemblyLite; aEnumStyle: EnumStyle; aUnknownPolicy: NrtUnknownPolicy): String;
    begin
      var sb := new StringBuilder;
      sb.AppendLine('// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.');
      sb.AppendLine();

      var byNamespace := new Dictionary<String, List<IrTypeLite>>;
      var order := new List<String>;
      for each t in aAssembly.Types do begin
        var key := t.NamespaceName;
        if String.IsNullOrEmpty(key) then key := '';
        if not byNamespace.ContainsKey(key) then begin
          byNamespace[key] := new List<IrTypeLite>;
          order.Add(key);
        end;
        byNamespace[key].Add(t);
      end;

      for each ns in order do begin
        var types := byNamespace[ns];
        var hasNs := not String.IsNullOrEmpty(ns);
        var pad := '';
        if hasNs then begin
          sb.AppendLine('declare namespace ' + ns + ' {');
          pad := '  ';
        end;

        for each t in types do
          EmitType(sb, t, aEnumStyle, aUnknownPolicy, pad);

        if hasNs then sb.AppendLine('}');
      end;

      result := sb.ToString();
    end;
  end;

end.
