// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace InertiaMode {
  export interface RoleDto {
    Name: string;
  }
  export interface UserDto {
    Email: string;
    Role: InertiaMode.RoleDto | null;
  }
  export interface MetaDto {
    Title: string;
  }
  export interface BadgeDto {
    Points: number;
  }
  export interface TagDto {
    Label: string;
  }
  export interface SharedUserDto {
    Email: string;
  }
}
declare namespace Props {
  export interface SharedData {
    flash: Record<string, string>;
    timestamp: string;
    errors: Record<string, string>;
    Auth: InertiaMode.SharedUserDto | null;
    AppName: string | null;
    Flash: string | null;
  }
  export interface ProfileProps extends Props.SharedData {
    User: InertiaMode.UserDto | null;
    IsAdmin: boolean;
    Bio: string | null;
    Meta: InertiaMode.MetaDto | null;
    Note: unknown | null;
    Age: number;
    Joined: string;
    Badge: InertiaMode.BadgeDto;
    Tags: InertiaMode.TagDto[] | null;
    Lookup: Record<string, InertiaMode.RoleDto> | null;
    SureTags: InertiaMode.TagDto[];
    MaybeNote: string | null;
    SavedAt: string | null;
  }
  export type ProfileFormErrors = Partial<Record<'User' | 'IsAdmin' | 'Bio' | 'Meta' | 'Note' | 'Age' | 'Joined' | 'Badge' | 'Tags' | 'Lookup' | 'SureTags' | 'MaybeNote' | 'SavedAt', string>>;
  export interface EmptyProps extends Props.SharedData {
  }
  export type EmptyFormErrors = Partial<Record<never, string>>;
}
