// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace InertiaMode {
  export interface RoleDto {
    name: string;
  }
  export interface UserDto {
    email: string;
    role: InertiaMode.RoleDto | null;
  }
  export interface MetaDto {
    title: string;
  }
  export interface SharedUserDto {
    email: string;
  }
}
declare namespace Props {
  export interface SharedData {
    flash: Record<string, string>;
    timestamp: string;
    errors: Record<string, string>;
    auth: InertiaMode.SharedUserDto | null;
    appName: string | null;
  }
  export interface ProfileProps extends Props.SharedData {
    user: InertiaMode.UserDto | null;
    isAdmin: boolean;
    bio: string | null;
    meta: InertiaMode.MetaDto | null;
    note: unknown | null;
    age: number;
    joined: string;
    savedAt: string | null;
  }
  export type ProfileFormErrors = Partial<Record<'user' | 'isAdmin' | 'bio' | 'meta' | 'note' | 'age' | 'joined' | 'savedAt', string>>;
  export interface EmptyProps extends Props.SharedData {
  }
  export type EmptyFormErrors = Partial<Record<never, string>>;
}
