// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace InertiaMode {
  export interface RoleDto {
    Name: string | null;
  }
  export interface UserDto {
    Email: string | null;
    Role: InertiaMode.RoleDto | null;
  }
  export interface MetaDto {
    Title: string | null;
  }
}
declare namespace Props {
  export interface ProfileProps {
    User: InertiaMode.UserDto | null;
    IsAdmin: boolean;
    Bio: string | null;
    Meta: InertiaMode.MetaDto | null;
    Note: unknown | null;
  }
}
