// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace InertiaMode {
  export interface RoleDto {
    Name: string;
  }
  export interface UserDto {
    Email: string;
    Role: InertiaMode.RoleDto;
  }
  export interface MetaDto {
    Title: string;
  }
}
declare namespace Props {
  export interface ProfileProps {
    User: InertiaMode.UserDto;
    IsAdmin: boolean;
    Bio: string;
    Meta: InertiaMode.MetaDto;
    Note: unknown;
  }
  export type ProfileFormErrors = Partial<Record<'User' | 'IsAdmin' | 'Bio' | 'Meta' | 'Note', string>>;
  export interface EmptyProps {
  }
  export type EmptyFormErrors = Partial<Record<never, string>>;
}
