// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace InertiaMode {
  export interface RoleDto {
    Name: string;
  }
  export interface UserDto {
    Email: string;
    Role: InertiaMode.RoleDto;
  }
  export interface MetaDto {
    Title: string;
  }
  export interface SharedUserDto {
    Email: string;
  }
}
declare namespace Props {
  export interface SharedData {
    flash: Record<string, string>;
    timestamp: string;
    errors: Record<string, string>;
    Auth: InertiaMode.SharedUserDto;
    AppName: string;
  }
  export interface ProfileProps extends Props.SharedData {
    User: InertiaMode.UserDto;
    IsAdmin: boolean;
    Bio: string;
    Meta: InertiaMode.MetaDto;
    Note: unknown;
  }
  export type ProfileFormErrors = Partial<Record<'User' | 'IsAdmin' | 'Bio' | 'Meta' | 'Note', string>>;
  export interface EmptyProps extends Props.SharedData {
  }
  export type EmptyFormErrors = Partial<Record<never, string>>;
}
