// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace InertiaMode {
  export interface RoleDto {
    name: string;
  }
  export interface UserDto {
    email: string;
    role: InertiaMode.RoleDto;
  }
  export interface MetaDto {
    title: string;
  }
  export interface SharedUserDto {
    email: string;
  }
}
declare namespace Props {
  export interface SharedData {
    flash: Record<string, string>;
    timestamp: string;
    errors: Record<string, string>;
    auth: InertiaMode.SharedUserDto;
    appName: string;
  }
  export interface ProfileProps extends Props.SharedData {
    user: InertiaMode.UserDto;
    isAdmin: boolean;
    bio: string;
    meta: InertiaMode.MetaDto;
    note: unknown;
    age: number;
  }
  export type ProfileFormErrors = Partial<Record<'user' | 'isAdmin' | 'bio' | 'meta' | 'note' | 'age', string>>;
  export interface EmptyProps extends Props.SharedData {
  }
  export type EmptyFormErrors = Partial<Record<never, string>>;
}
