// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace TokenizerEdgeCases {
  export interface Tricky {
    afterCommentSayingNullable: string | null;
    afterBlockComment: string | null;
    afterXmlDocComment: string | null;
    withKeywordDefault: string;
    afterKeywordDefault: string | null;
    explicitlyNullable: string | null;
    explicitlyNotNullable: string;
    firstName: string | null;
    lastName: string | null;
  }
}
