// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace TokenizerEdgeCases {
  export interface Tricky {
    AfterCommentSayingNullable: string | null;
    AfterBlockComment: string | null;
    AfterXmlDocComment: string | null;
    WithKeywordDefault: string;
    AfterKeywordDefault: string | null;
    ExplicitlyNullable: string | null;
    ExplicitlyNotNullable: string;
    FirstName: string | null;
    LastName: string | null;
  }
}
