// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace TokenizerEdgeCases {
  export interface Tricky {
    afterCommentSayingNullable: string; // nrt: unknown
    afterBlockComment: string; // nrt: unknown
    afterXmlDocComment: string; // nrt: unknown
    withKeywordDefault: string;
    afterKeywordDefault: string; // nrt: unknown
    explicitlyNullable: string | null;
    explicitlyNotNullable: string;
    firstName: string | null;
    lastName: string | null;
  }
}
