// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace TokenizerEdgeCases {
  export interface Tricky {
    AfterCommentSayingNullable: string; // nrt: unknown
    AfterBlockComment: string; // nrt: unknown
    AfterXmlDocComment: string; // nrt: unknown
    WithKeywordDefault: string;
    AfterKeywordDefault: string; // nrt: unknown
    ExplicitlyNullable: string | null;
    ExplicitlyNotNullable: string;
    FirstName: string | null;
    LastName: string | null;
  }
}
