// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace TokenizerEdgeCases {
  export interface Tricky {
    afterCommentSayingNullable: string;
    afterBlockComment: string;
    afterXmlDocComment: string;
    withKeywordDefault: string;
    afterKeywordDefault: string;
    explicitlyNullable: string | null;
    explicitlyNotNullable: string;
    firstName: string | null;
    lastName: string | null;
  }
}
