// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace SampleModel {
  export enum Status {
    Active = 0,
    Inactive = 1,
    Pending = 2,
  }
  export interface Rating {
    Aroma: number;
    Taste: number;
    Overall: number;
  }
  export interface User {
    Id: string;
    DisplayName: string | null;
    Age: number;
    IsAdmin: boolean;
    Notes: string | null;
    CurrentStatus: SampleModel.Status;
    RegisteredOn: string;
    CurrentRating: SampleModel.Rating;
    FirstName: string | null;
    LastName: string | null;
  }
}
