// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace SampleModel {
  export enum Status {
    Active = 0,
    Inactive = 1,
    Pending = 2,
  }
  export interface User {
    id: string;
    displayName: string | null;
    age: number;
    isAdmin: boolean;
    notes: string; // nrt: unknown
    firstName: string | null;
    lastName: string | null;
  }
}
