// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace SampleModel {
  export type Status = "Active" | "Inactive" | "Pending";
  export interface Rating {
    aroma: number;
    taste: number;
    overall: number;
  }
  export interface User {
    id: string;
    displayName: string | null;
    age: number;
    isAdmin: boolean;
    notes: string;
    currentStatus: SampleModel.Status;
    registeredOn: string;
    currentRating: SampleModel.Rating;
    firstName: string | null;
    lastName: string | null;
  }
}
