// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace SampleModel {
  export type Status = "Active" | "Inactive" | "Pending";
  export interface User {
    Id: string;
    DisplayName: string | null;
    Age: number;
    IsAdmin: boolean;
    FirstName: string | null;
    LastName: string | null;
  }
}
