// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace Generics {
  export interface Tag {
    Label: string;
  }
  export interface Node {
    Value: string;
    Children: Generics.Node[] | null;
    Tags: Generics.Tag[] | null;
    Scores: number[] | null;
    Lookup: Record<string, number> | null;
    MaybeCount: number | null;
    Numbers: number[] | null;
  }
}
