// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace Generics {
  export interface Tag {
    label: string;
  }
  export interface Node {
    value: string;
    children: Generics.Node[] | null;
    tags: Generics.Tag[] | null;
    scores: number[] | null;
    lookup: Record<string, number> | null;
    maybeCount: number | null;
    numbers: number[] | null;
  }
}
