// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace Generics {
  export interface Tag {
    Label: string;
  }
  export interface Node {
    Value: string;
    Children: Generics.Node[];
    Tags: Generics.Tag[];
    Scores: number[];
    Lookup: Record<string, number>;
    MaybeCount: number | null;
    Numbers: number[];
  }
}
