// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace Generics {
  export interface Tag {
    label: string;
  }
  export interface Node {
    value: string;
    children: Generics.Node[];
    tags: Generics.Tag[];
    scores: number[];
    lookup: Record<string, number>;
    maybeCount: number | null;
    numbers: number[];
  }
}
