// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace MultiTypeAndIndexer {
  export enum Kind {
    Foo = 0,
    Bar = 1,
  }
  export interface Alpha {
    Name: string | null;
  }
  export interface Beta {
    Name: string;
    Item: string;
    Count: number | null;
  }
}
