// AUTO-GENERATED by oxygene-tsgen. Do not edit by hand.

declare namespace MultiTypeAndIndexer {
  export enum Kind {
    Foo = 0,
    Bar = 1,
  }
  export interface Alpha {
    name: string | null;
  }
  export interface Beta {
    name: string;
    item: string;
    count: number;
  }
}
